/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biofiliaproject.contenedores;

import biofiliaproject.preguntas.Final;
import static biofiliaproject.preguntas.Nature.cursoAlumno;
import static biofiliaproject.preguntas.Nature.nombreAlumno;
import com.mysql.jdbc.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;

/**
 *
 * @author 47448880
 */
public class ConInicio extends javax.swing.JFrame {

    final int ID_IMAGEN=1;
    /**
     * Creates new form EmPantalla1
     */
    public ConInicio() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_emPantalla1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombreAlumno = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cursoAlumno = new javax.swing.JLabel();
        btn_siguiente = new javax.swing.JButton();
        em_imagen = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_siguiente1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1020, 720));

        panel_emPantalla1.setPreferredSize(new java.awt.Dimension(1020, 720));

        jLabel1.setText("Alumno:");

        nombreAlumno.setText("Nombre");

        jLabel3.setText("Curso:");

        cursoAlumno.setText("XX");

        btn_siguiente.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_siguiente.setText("SIGUIENTE");
        btn_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_siguienteActionPerformed(evt);
            }
        });

        em_imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biofiliaproject/rsc/containers/contenedores.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel2.setText("¿CONOCES LOS CONTENEDORES?");

        btn_siguiente1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_siguiente1.setText("SALTAR AL FINAL");
        btn_siguiente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_siguiente1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_emPantalla1Layout = new javax.swing.GroupLayout(panel_emPantalla1);
        panel_emPantalla1.setLayout(panel_emPantalla1Layout);
        panel_emPantalla1Layout.setHorizontalGroup(
            panel_emPantalla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_emPantalla1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreAlumno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cursoAlumno)
                .addGap(24, 24, 24))
            .addGroup(panel_emPantalla1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_siguiente)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btn_siguiente1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panel_emPantalla1Layout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addComponent(em_imagen)
                .addContainerGap(138, Short.MAX_VALUE))
            .addGroup(panel_emPantalla1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_emPantalla1Layout.setVerticalGroup(
            panel_emPantalla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_emPantalla1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panel_emPantalla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(nombreAlumno)
                    .addComponent(cursoAlumno))
                .addGap(61, 61, 61)
                .addComponent(jLabel2)
                .addGap(39, 39, 39)
                .addComponent(em_imagen)
                .addGap(50, 50, 50)
                .addGroup(panel_emPantalla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_siguiente)
                    .addComponent(btn_siguiente1))
                .addContainerGap(273, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_emPantalla1, javax.swing.GroupLayout.DEFAULT_SIZE, 1064, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_emPantalla1, javax.swing.GroupLayout.DEFAULT_SIZE, 1042, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_siguienteActionPerformed

        ConPantalla1 conpant1 = new ConPantalla1();
        conpant1.setVisible(true);
            
        String nombre = nombreAlumno.getText();
        String curso = cursoAlumno.getText();
            
        conpant1.nombreAlumno.setText(nombre);
        conpant1.cursoAlumno.setText(curso);
        dispose();

    }//GEN-LAST:event_btn_siguienteActionPerformed

    private void btn_siguiente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_siguiente1ActionPerformed
        Final pantfinal = new Final();
        pantfinal.setVisible(true);
            
        String nombre = nombreAlumno.getText();
        String curso = cursoAlumno.getText();
            
        pantfinal.nombreAlumno.setText(nombre);
        pantfinal.cursoAlumno.setText(curso);
        dispose();
    }//GEN-LAST:event_btn_siguiente1ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConInicio().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_siguiente;
    private javax.swing.JButton btn_siguiente1;
    public static javax.swing.JLabel cursoAlumno;
    private javax.swing.JLabel em_imagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel nombreAlumno;
    private javax.swing.JPanel panel_emPantalla1;
    // End of variables declaration//GEN-END:variables
}
